INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('IFAC', 'Instituto Federal do Acre', 'Pública', 3);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UFAC', 'Universidade Federal do Acre', 'Pública', 2);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UNEAL', 'Universidade Estadual de Alagoas', 'Pública', 3);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UNCISAL', 'Universidade Estadual de Ciências da Saúde de Alagoas', 'Pública', 4);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('CESMAC', 'Centro de Estudos Superiores de Maceió', 'Privada', 2);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('FAP', 'Faculdade Pitágoras', 'Privada', 4);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('FITS', 'Faculdade Integrada Tiradentes', 'Privada', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UNESP', 'Universidade Estadual Paulista', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('MACKENZIE', 'Universidade Presbiteriana Mackenzie', 'Privada', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UEAP', 'Universidade Estadual do Amapá', 'Pública', 4);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('IFAP', 'Instituto Federal do Amapá', 'Pública', 1);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('Unifap', 'Universidade Federal do Amapá', 'Pública', 4);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UFBA', 'Universidade Federal da Bahia', 'Pública', 4);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('CEAP', 'Centro de Ensino Superior do Amapá', 'Privada', 2);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('SEAMA', 'Faculdade SEAMA', 'Privada', 0);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UEA', 'Universidade do Estado do Amazonas', 'Pública', 1);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('IFAM', 'Instituto Federal do Amazonas', 'Pública', 4);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UFAM', 'Universidade Federal do Amazonas', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('ULBRA', 'Universidade Luterana do Brasil', 'Privada', 3);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('Unisalle', 'Faculdade La Salle', 'Privada', 0);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UECE', 'Universidade Estadual do Ceará', 'Pública', 0);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('FALS', 'Faculdade de Ciências Aplicadas Doutor Leão Sampaio', 'Privada', 3);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UnB', 'Universidade de Brasília', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('CEUB', 'Centro Universitário de Brasília', 'Privada', 3);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('ITA', 'Instituto Tecnológico de Aeronáutica', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UNIFESP', 'Universidade Federal de São Paulo', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UFMT', 'Universidade Federal de Mato Grosso', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UFMG', 'Universidade Federal de Minas Gerais', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UFRJ', 'Universidade Federal do Rio de Janeiro', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UFSCar', 'Universidade Federal de São Carlos', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UNIP', 'Universidade Paulista', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('FGV', 'Fundação Getulio Vargas', 'Privada', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('USP', 'Universidade de São Paulo', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('PUCSP', 'Pontifícia Universidade Católica de São Paulo', 'Privada', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('PUCRJ', 'Pontifícia Universidade Católica do Rio de Janeiro', 'Privada', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UFPR', 'Universidade Federal do Paraná', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('IFSP', 'Instituto Federal de São Paulo', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UNICAMP', 'Universidade Estadual de Campinas', 'Pública', 5);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UNIRIO', 'Universidade Federal do Estado do Rio de Janeiro', 'Pública', 4);
INSERT INTO instituicao (sigla, nome_instituicao, natureza_administrativa, nota_IGC) VALUES ('UFSC', 'Universidade Federal de Santa Catarina', 'Pública', 5);

INSERT INTO campus VALUES ('Rio Branco', 'AC', 'Rio Branco', '1');
INSERT INTO campus VALUES ('Cruzeiro do Sul', 'AC', 'Cruzeiro do Sul', '2');
INSERT INTO campus VALUES ('Arapiraca', 'AL', 'Arapiraca', '3');
INSERT INTO campus VALUES ('Governador Lamenha Filho', 'AL', 'Maceió', '4');
INSERT INTO campus VALUES ('Maceió', 'AL', 'Maceió', '5');
INSERT INTO campus VALUES ('Maceió', 'AL', 'Maceió', '6');
INSERT INTO campus VALUES ('Piedade', 'AL', 'Piedade', '7');
INSERT INTO campus VALUES ('Botucatu', 'SP', 'Botucatu', '8');
INSERT INTO campus VALUES ('Consolação', 'SP', 'São Paulo', '9');
INSERT INTO campus VALUES ('Graziela', 'AP', 'Macapá', '10');
INSERT INTO campus VALUES ('Laranjal', 'AP', 'Vitória do Jari', '11');
INSERT INTO campus VALUES ('Jardim Marco Zero', 'AP', 'Macapá', '12');
INSERT INTO campus VALUES ('Salvador', 'BA', 'Salvador', '13');
INSERT INTO campus VALUES ('Macapá', 'AP', 'Macapá', '14');
INSERT INTO campus VALUES ('Macapá', 'AP', 'Macapá', '15');
INSERT INTO campus VALUES ('Tefé', 'AM', 'Tefé', '16');
INSERT INTO campus VALUES ('Paritins', 'AM', 'Paritins', '17');
INSERT INTO campus VALUES ('Manaus', 'AM', 'Manaus', '18');
INSERT INTO campus VALUES ('Manaus', 'AM', 'Manaus', '19');
INSERT INTO campus VALUES ('Manaus', 'AM', 'Manaus', '20');
INSERT INTO campus VALUES ('Itaperi', 'CE', 'Fortaleza', '21');
INSERT INTO campus VALUES ('Saúde', 'CE', 'Juazeiro do Norte', '22');
INSERT INTO campus VALUES ('Ceilândia', 'DF', 'Brasília', '23');
INSERT INTO campus VALUES ('Taguatinga', 'DF', 'Brasília', '24');
INSERT INTO campus VALUES ('Departamento de Ciência e Tecnologia Aeroespacial', 'SP', 'São Paulo', '25');
INSERT INTO campus VALUES ('Osasco', 'SP', 'Osasco', '26');
INSERT INTO campus VALUES ('Cuiabá', 'MT', 'Cuiabá', '27');
INSERT INTO campus VALUES ('Pampulha', 'MG', 'Belo Horizonte', '28');
INSERT INTO campus VALUES ('Rio de Janeiro', 'RJ', 'Rio de Janeiro', '29');
INSERT INTO campus VALUES ('São Carlos', 'SP', 'São Carlos', '30');
INSERT INTO campus VALUES ('Sorocaba', 'SP', 'Sorocaba', '31');
INSERT INTO campus VALUES ('Paulista', 'SP', 'São Paulo', '32');
INSERT INTO campus VALUES ('São Paulo', 'SP', 'São Paulo', '33');
INSERT INTO campus VALUES ('Sorocaba', 'SP', 'Sorocaba', '34');
INSERT INTO campus VALUES ('Rio de Janeiro', 'RJ', 'Rio de Janeiro', '35');
INSERT INTO campus VALUES ('Batel', 'PR', 'Curitiba', '36');
INSERT INTO campus VALUES ('Salto', 'SP', 'Salto', '37');
INSERT INTO campus VALUES ('Piracicaba', 'SP', 'Piracicaba', '38');
INSERT INTO campus VALUES ('Instituto Biomédico', 'RJ', 'Rio de Janeiro', '39');
INSERT INTO campus VALUES ('Florianópolis', 'SC', 'Florianópolis', '40');
INSERT INTO campus VALUES ('Sorocaba', 'SP', 'Sorocaba', '29');
INSERT INTO campus VALUES ('São Carlos', 'SP', 'São Carlos', '30');
INSERT INTO campus VALUES ('Alphaville', 'SP', 'Santana de Parnaíba', '31');
INSERT INTO campus VALUES ('Ribeirão Preto', 'SP', 'Ribeirão Preto', '30');
INSERT INTO campus VALUES ('Bairro Universitário', 'MG', 'Montes Claros', '28');
INSERT INTO campus VALUES ('Guarulhos', 'SP', 'Guarulhos', '26');
INSERT INTO campus VALUES ('Rondonópolis', 'MT', 'Rondonópolis', '27');
INSERT INTO campus VALUES ('Bauru', 'SP', 'Bauru', '30');
INSERT INTO campus VALUES ('Higienópolis', 'SP', 'São Paulo', '9');
INSERT INTO campus VALUES ('Barão Geraldo', 'SP', 'Campinas', '38');

INSERT INTO curso VALUES ('Matemática', 'Ciências Exatas e da Terra', 5, 'Bacharelado', 'Integral', 6, 2000, '33');
INSERT INTO curso VALUES ('Ciência da computação', 'Ciências Exatas e da Terra', 5, 'Bacharelado', 'Noturno', 12, 2005, '33');
INSERT INTO curso VALUES ('Ciência agrária', 'Ciências Agrárias', 4, 'Licenciatura', 'Matutino', 10, 2001, '33');
INSERT INTO curso VALUES ('Ciências biológicas', 'Ciências Biológicas', 1, 'Doutorado', 'Vespertino', 2, 2010, '33');
INSERT INTO curso VALUES ('Filosofia', 'Ciências Humanas', 4, 'Mestrado', 'Integral', 5, 2003, '33');
INSERT INTO curso VALUES ('História', 'Ciências Humanas', 3, 'Mestrado', 'Vespertino', 3, 2011, '33');
INSERT INTO curso VALUES ('Geografia', 'Ciências Humanas', 1, 'Doutorado', 'Matutino', 4, 2007, '19');
INSERT INTO curso VALUES ('Ciências sociais', 'Outros', 0, 'Licenciatura', 'Matutino', 7, 2008, '19');
INSERT INTO curso VALUES ('Engenharia da computação', 'Engenharias', 5, 'Bacharelado', 'Noturno', 9, 2009, '19');
INSERT INTO curso VALUES ('Ciência da computação', 'Ciências Exatas e da Terra', 5, 'Licenciatura', 'Integral', 10, 2006, '19');
INSERT INTO curso VALUES ('Ciências exatas', 'Ciências Exatas e da Terra', 4, 'Bacharelado', 'Noturno', 12, 2003, '19');
INSERT INTO curso VALUES ('Ciências da aeronáutica', 'Engenharias', 3, 'Doutorado', 'Integral', 10, 2008, '19');
INSERT INTO curso VALUES ('Engenharia da computação', 'Engenharias', 5, 'Doutorado', 'Noturno', 2, 2010, '23');
INSERT INTO curso VALUES ('Ciência marítima', 'Ciências Biológicas', 2, 'Bacharelado', 'Integral', 10, 2019, '23');
INSERT INTO curso VALUES ('Biologia', 'Ciências Biológicas', 2, 'Licenciatura', 'Noturno', 12, 2019, '23');
INSERT INTO curso VALUES ('Química', 'Ciências Exatas e da Terra', 1, 'Mestrado', 'Matutino', 9, 2012, '23');
INSERT INTO curso VALUES ('Administração', 'Ciências Sociais Aplicadas', 0, 'Doutorado', 'Vespertino', 8, 2013, '23');
INSERT INTO curso VALUES ('Economia', 'Ciências Sociais Aplicadas', 4, 'Tecnólogo', 'Vespertino', 7, 2014, '23');
INSERT INTO curso VALUES ('Economia', 'Ciências Sociais Aplicadas', 4, 'Tecnólogo', 'Matutino', 1, 2015, '4');
INSERT INTO curso VALUES ('Ciências econômicas', 'Ciências Sociais Aplicadas', 2, 'Mestrado', 'Vespertino', 10, 2017, '4');
INSERT INTO curso VALUES ('Ciências exatas', 'Ciências Exatas e da Terra', 3, 'Bacharelado', 'Integral', 12, 2019, '4');
INSERT INTO curso VALUES ('Matemática', 'Ciências Exatas e da Terra', 3, 'Mestrado', 'Integral', 9, 2000, '4');
INSERT INTO curso VALUES ('Biologia', 'Ciências Biológicas', 5, 'Doutorado', 'Integral', 4, 2004, '8');
INSERT INTO curso VALUES ('Engenharia civil', 'Engenharias', 5, 'Tecnólogo', 'Vespertino', 5, 2006, '8');
INSERT INTO curso VALUES ('Engenharia naval', 'Engenharias', 1, 'Tecnólogo', 'Integral', 3, 2002, '8');
INSERT INTO curso VALUES ('Engenharia da computação', 'Engenharias', 5, 'Licenciatura', 'Matutino', 2, 2011, '8');
INSERT INTO curso VALUES ('História', 'Ciências Humanas', 5, 'Bacharelado', 'Noturno', 10, 2003, '8');
INSERT INTO curso VALUES ('Geografia', 'Ciências Humanas', 5, 'Bacharelado', 'Noturno', 12, 2001, '15');
INSERT INTO curso VALUES ('Direito', 'Ciências Sociais Aplicadas', 5, 'Tecnólogo', 'Noturno', 9, 2010, '15');
INSERT INTO curso VALUES ('Direito civil', 'Ciências Sociais Aplicadas', 4, 'Mestrado', 'Matutino', 7, 2009, '15');
INSERT INTO curso VALUES ('Jogos digitais', 'Outros', 0, 'Bacharelado', 'Integral', 9, 2010, '15');
INSERT INTO curso VALUES ('Medicina', 'Ciências da Saúde', 5, 'Bacharelado', 'Integral', 11, 2011, '16');
INSERT INTO curso VALUES ('Ciência agrária', 'Ciências Agrárias', 4, 'Bacharelado', 'Noturno', 12, 2012, '16');
INSERT INTO curso VALUES ('Matemática', 'Ciências Exatas e da Terra', 3, 'Doutorado', 'Vespertino', 10, 2012, '23');
INSERT INTO curso VALUES ('Ciência da computação', 'Ciências Exatas e da Terra', 1, 'Bacharelado', 'Integral', 9, 2001, '23');
INSERT INTO curso VALUES ('Biologia', 'Ciências Biológicas', 5, 'Doutorado', 'Noturno', 4, 2007, '42');
INSERT INTO curso VALUES ('Química', 'Ciências Exatas e da Terra', 3, 'Bacharelado', 'Vespertino', 3, 2004, '42');
INSERT INTO curso VALUES ('Ciências econômicas', 'Ciências Sociais Aplicadas', 4, 'Bacharelado', 'Vespertino', 2, 2003, '11');
INSERT INTO curso VALUES ('Matemática', 'Ciências Exatas e da Terra', 3, 'Licenciatura', 'Matutino', 7, 2010, '1');
INSERT INTO curso VALUES ('Filosofia', 'Ciências Humanas', 0, 'Licenciatura', 'Integral', 10, 2011, '1');
INSERT INTO curso VALUES ('Direito', 'Ciências Sociais Aplicadas', 4, 'Bacharelado', 'Integral', 4, 2007, '7');
INSERT INTO curso VALUES ('Medicina', 'Ciências da Saúde', 5, 'Bacharelado', 'Noturno', 6, 2005, '7');
INSERT INTO curso VALUES ('Economia', 'Ciências Sociais Aplicadas', 1, 'Mestrado', 'Vespertino', 3, 2003, '10');
INSERT INTO curso VALUES ('Economia avançada', 'Ciências Sociais Aplicadas', 0, 'Tecnólogo', 'Vespertino', 12, 2007, '10');
INSERT INTO curso VALUES ('Matemática', 'Ciências Exatas e da Terra', 2, 'Tecnólogo', 'Vespertino', 11, 2009, '35');
INSERT INTO curso VALUES ('Jogos digitais', 'Outros', 1, 'Doutorado', 'Vespertino', 10, 2008, '35');
INSERT INTO curso VALUES ('Administração', 'Ciências Sociais Aplicadas', 5, 'Mestrado', 'Integral', 1, 2000, '12');
INSERT INTO curso VALUES ('Administração de empresas', 'Ciências Sociais Aplicadas', 5, 'Licenciatura', 'Noturno', 5, 2003, '12');
INSERT INTO curso VALUES ('Engenharia civil', 'Engenharias', 4, 'Bacharelado', 'Integral', 4, 2002, '2');
INSERT INTO curso VALUES ('Engenharia naval', 'Engenharias', 3, 'Licenciatura', 'Matutino', 7, 2000, '2');
INSERT INTO curso VALUES ('Engenharia civil', 'Engenharias', 4, 'Bacharelado', 'Integral', 6, 2001, 'São Carlos', 'UFSCar');
INSERT INTO curso VALUES ('Ciência da computação', 'Ciências Exatas e da Terra', 5, 'Bacharelado', 'Noturno', 12, 2005, 'São Carlos', 'UFSCar');
INSERT INTO curso VALUES ('Ciência agrária', 'Ciências Agrárias', 1, 'Licenciatura', 'Matutino', 10, 2001, 'Ceilândia', 'UnB');
INSERT INTO curso VALUES ('Ciências biológicas', 'Ciências Biológicas', 0, 'Doutorado', 'Vespertino', 2, 2010, 'Ceilândia', 'UnB');
INSERT INTO curso VALUES ('Filosofia', 'Ciências Humanas', 4, 'Mestrado', 'Integral', 5, 2003, 'Alphaville', 'UNIP');
INSERT INTO curso VALUES ('Direito', 'Ciências Sociais Aplicadas', 0, 'Tecnólogo', 'Noturno', 9, 2010, 'Alphaville', 'UNIP');
INSERT INTO curso VALUES ('Ciências exatas', 'Ciências Exatas e da Terra', 3, 'Doutorado', 'Integral', 10, 2019, 'Florianópolis', 'UFSC');
INSERT INTO curso VALUES ('Engenharia da computação', 'Engenharias', 5, 'Doutorado', 'Noturno', 2, 2018, 'Florianópolis', 'UFSC');
INSERT INTO curso VALUES ('Relações Públicas', 'Outros', 4, 'Bacharelado', 'Integral', 7, 2010, '11');
INSERT INTO curso VALUES ('Administração Hospitalar', 'Outros', 2, 'Tecnólogo', 'Noturno', 4, 1981, '11');
INSERT INTO curso VALUES ('Biomedicina', 'Outros', 5, 'Mestrado', 'Matutino', 8, 1995, '11');
INSERT INTO curso VALUES ('Arquitetura', 'Ciências Sociais Aplicadas', 5, 'Bacharelado', 'Integral', 10, 2006, '11');
INSERT INTO curso VALUES ('Ecologia', 'Ciências Biológicas', 5, 'Bacharelado', 'Vespertino', 10, 2006, '11');
INSERT INTO curso VALUES ('Bioquímica', 'Ciências Biológicas', 2, 'Bacharelado', 'Vespertino', 7, 2008, '11');
INSERT INTO curso VALUES ('Letras', 'Linguística, Letras e Artes', 1, 'Licenciatura', 'Integral', 9, 2012, 'Alphaville', 'UNIP');
INSERT INTO curso VALUES ('Fotografia', 'Linguística, Letras e Artes', 0, 'Tecnólogo', 'Matutino', 6, 1981, 'Alphaville', 'UNIP');
INSERT INTO curso VALUES ('Teoria Literária', 'Linguística, Letras e Artes', 4, 'Mestrado', 'Noturno', 10, 1990, 'Alphaville', 'UNIP');
INSERT INTO curso VALUES ('Arquitetura', 'Ciências Sociais Aplicadas', 0, 'Licenciatura', 'Integral', 4, 2005, 'Alphaville', 'UNIP');
INSERT INTO curso VALUES ('Engenharia Elétrica', 'Engenharias', 5, 'Bacharelado', 'Integral', 12, 2002, 'Alphaville', 'UNIP');
INSERT INTO curso VALUES ('Biofísica', 'Ciências Biológicas', 5, 'Mestrado', 'Integral', 9, 2007, 'Alphaville', 'UNIP');
INSERT INTO curso VALUES ('Farmacologia', 'Ciências Biológicas', 3, 'Mestrado', 'Vespertino', 10, 2002, 'Alphaville', 'UNIP');
INSERT INTO curso VALUES ('Letras', 'Linguística, Letras e Artes', 5, 'Mestrado', 'Matutino', 10, 2016, '16');
INSERT INTO curso VALUES ('Arte audiovisual', 'Linguística, Letras e Artes', 3, 'Tecnólogo', 'Noturno', 11, 1992, '16');
INSERT INTO curso VALUES ('Artes Plásticas', 'Linguística, Letras e Artes', 5, 'Doutorado', 'Matutino', 12, 1999, '16');
INSERT INTO curso VALUES ('Sociologia', 'Ciências Humanas', 2, 'Doutorado', 'Noturno', 4, 1998, '16');
INSERT INTO curso VALUES ('Engenharia Química', 'Engenharias', 1, 'Doutorado', 'Integral', 12, 1999, '16');
INSERT INTO curso VALUES ('Teoria Literária', 'Linguística, Letras e Artes', 4, 'Mestrado', 'Noturno', 8, 2012, '7');
INSERT INTO curso VALUES ('Arte audiovisual', 'Linguística, Letras e Artes', 0, 'Bacharelado', 'Noturno', 6, 1993, '7');
INSERT INTO curso VALUES ('Artes Plásticas', 'Linguística, Letras e Artes', 2, 'Doutorado', 'Integral', 10, 2000, '7');
INSERT INTO curso VALUES ('Engenharia de Transportes', 'Engenharias', 5, 'Doutorado', 'Integral', 10, 1981, '7');
INSERT INTO curso VALUES ('Engenharia Aeroespacial', 'Engenharias', 4, 'Licenciatura', 'Integral', 10, 2005, '7');
INSERT INTO curso VALUES ('Música', 'Linguística, Letras e Artes', 1, 'Bacharelado', 'Noturno', 7, 2009, 'Ceilândia', 'UnB');
INSERT INTO curso VALUES ('Letras', 'Linguística, Letras e Artes', 1, 'Bacharelado', 'Integral', 4, 1994, 'Ceilândia', 'UnB');
INSERT INTO curso VALUES ('Engenharia Mecatrônica', 'Outros', 4, 'Bacharelado', 'Integral', 11, 2002, 'Ceilândia', 'UnB');
INSERT INTO curso VALUES ('Sociologia', 'Ciências Humanas', 5, 'Bacharelado', 'Integral', 4, 1995, 'Ceilândia', 'UnB');
INSERT INTO curso VALUES ('Relações Internacionais', 'Outros', 5, 'Bacharelado', 'Noturno', 7, 2008, 'São Carlos', 'UFSCar');
INSERT INTO curso VALUES ('Sociologia', 'Ciências Humanas', 5, 'Bacharelado', 'Integral', 4, 1995, 'São Carlos', 'UFSCar');
INSERT INTO curso VALUES ('Biomedicina', 'Outros', 4, 'Licenciatura', 'Integral', 11, 2003, 'São Carlos', 'UFSCar');
INSERT INTO curso VALUES ('Geografia', 'Ciências Humanas', 0, 'Bacharelado', 'Integral', 8, 1996, 'São Carlos', 'UFSCar');
INSERT INTO curso VALUES ('Psicologia', 'Ciências Humanas', 5, 'Mestrado', 'Integral', 5, 1997, 'São Carlos', 'UFSCar');
INSERT INTO curso VALUES ('Ciência Política', 'Ciências Humanas', 4, 'Bacharelado', 'Integral', 6, 1997, 'São Carlos', 'UFSCar');
INSERT INTO curso VALUES ('Relações Internacionais', 'Outros', 5, 'Licenciatura', 'Noturno', 7, 2007, '2');
INSERT INTO curso VALUES ('Sociologia', 'Ciências Humanas', 5, 'Bacharelado', 'Integral', 4, 2005, '2');
INSERT INTO curso VALUES ('Biomedicina', 'Outros', 4, 'Bacharelado', 'Integral', 11, 2003, '2');
INSERT INTO curso VALUES ('Geografia', 'Ciências Humanas', 5, 'Bacharelado', 'Vespertino', 8, 2010, '2');
INSERT INTO curso VALUES ('Psicologia', 'Ciências Humanas', 5, 'Mestrado', 'Integral', 10, 2018, '2');
INSERT INTO curso VALUES ('Ciência Política', 'Ciências Humanas', 2, 'Licenciatura', 'Integral', 12, 2004, '2');
INSERT INTO curso VALUES ('Desenho Industrial', 'Ciências Sociais Aplicadas', 5, 'Doutorado', 'Noturno', 7, 2007, '10');
INSERT INTO curso VALUES ('Sociologia', 'Ciências Humanas', 5, 'Tecnólogo', 'Vespertino', 4, 2015, '10');
INSERT INTO curso VALUES ('Medicina', 'Ciências da Saúde', 5, 'Bacharelado', 'Integral', 12, 2002, '10');
INSERT INTO curso VALUES ('Direito', 'Ciências Sociais Aplicadas', 2, 'Bacharelado', 'Integral', 8, 2011, '10');
INSERT INTO curso VALUES ('Economia Geral', 'Ciências Sociais Aplicadas', 1, 'Mestrado', 'Matutino', 10, 2014, '10');
INSERT INTO curso VALUES ('Engenharia Têxtil', 'Outros', 2, 'Tecnólogo', 'Integral', 12, 2004, '10');
INSERT INTO curso VALUES ('Nutrição', 'Ciências da Saúde', 3, 'Bacharelado', 'Noturno', 12, 2009, '19');
INSERT INTO curso VALUES ('Enfermagem', 'Ciências da Saúde', 5, 'Bacharelado', 'Vespertino', 10, 2018, '19');
INSERT INTO curso VALUES ('Odontologia', 'Ciências da Saúde', 4, 'Bacharelado', 'Integral', 11, 2010, '19');
INSERT INTO curso VALUES ('Educação Física', 'Ciências da Saúde', 5, 'Bacharelado', 'Integral', 8, 2011, '19');
INSERT INTO curso VALUES ('Psiquiatria', 'Ciências da Saúde', 0, 'Mestrado', 'Integral', 6, 2012, '19');
INSERT INTO curso VALUES ('Saúde Pública', 'Ciências da Saúde', 4, 'Bacharelado', 'Noturno', 6, 2016, '19');
INSERT INTO curso VALUES ('Agronomia', 'Ciências Agrárias', 3, 'Bacharelado', 'Noturno', 10, 1981, '33');
INSERT INTO curso VALUES ('Engenharia Agrícola', 'Ciências Agrárias', 5, 'Licenciatura', 'Matutino', 10, 2000, '33');
INSERT INTO curso VALUES ('Zootecnia', 'Ciências Agrárias', 4, 'Mestrado', 'Vespertino', 11, 2001, '33');
INSERT INTO curso VALUES ('Engenharia de Alimentos', 'Ciências Agrárias', 5, 'Tecnólogo', 'Integral', 8, 2011, '33');
INSERT INTO curso VALUES ('Tecnologia de Alimentos', 'Ciências Agrárias', 0, 'Mestrado', 'Integral', 6, 2007, '33');
INSERT INTO curso VALUES ('Medicina Veterinária', 'Ciências Agrárias', 4, 'Bacharelado', 'Noturno', 6, 2016, '33');
INSERT INTO curso VALUES ('Enfermagem', 'Ciências da Saúde', 5, 'Bacharelado', 'Matutino', 10, 2014, '33');
INSERT INTO curso VALUES ('Farmacologia', 'Ciências Biológicas', 5, 'Tecnólogo', 'Matutino', 11, 2013, '33');
INSERT INTO curso VALUES ('Estatística', 'Ciências Exatas e da Terra', 5, 'Bacharelado', 'Vespertino', 12, 2010, '42');
INSERT INTO curso VALUES ('Física', 'Ciências Exatas e da Terra', 2, 'Licenciatura', 'Matutino', 4, 1999, '42');
INSERT INTO curso VALUES ('Engenharia Civil', 'Engenharias', 4, 'Doutorado', 'Vespertino', 3, 2004, '42');